Update capsule to v0.10.0 and ckb-std to v0.13.0
cryptape/ckb-combine-lock-poc pull request #30
Opened 2023-05-10 08:43 UTC by mohanson

Update capsule to v0.10.0 and ckb-std to v0.13.0

2023-05-10 09:00 UTC, XuJiandong requested changes

2023-05-10 09:23 UTC, mohanson commented on Makefile
> +	cargo install cross --git https://github.com/cross-rs/cross
capsule 0.10.0 will use it.

2023-05-10 09:25 UTC, mohanson commented on contracts/ckb-combine-lock/src/main.rs
> +#[cfg(not(test))]
This is part of the template code generated by capsule v0.10.0

2023-05-12 02:51 UTC, XuJiandong approved these changes

2023-05-12 02:51 UTC, merged