Implement new ckb-combine-lock
cryptape/ckb-combine-lock-poc pull request #31
Opened 2023-05-12 03:04 UTC by mohanson

Type the following command to test the new combine-lock

```
$ make -C ckb-debugger-tests cl-always-success-v2
```

2023-05-12 03:10 UTC, XuJiandong commented
We don't need "v2": just replace origina one.

2023-05-12 03:10 UTC, mohanson commented
> We don't need "v2": just replace origina one.

OK

2023-05-12 04:10 UTC, XuJiandong requested changes

2023-05-15 05:57 UTC, XuJiandong requested changes

2023-05-15 05:57 UTC, XuJiandong commented on contracts/ckb-combine-lock-v2/src/entry.rs
> +        let data = ckb_std::env::argv()[1].to_bytes();
len() should be 2

2023-05-15 05:57 UTC, XuJiandong commented on contracts/ckb-combine-lock-v2/src/entry.rs
> +            Ok(()) => Ok(WitnessArgs::new_unchecked(data.into())),
This argument should be a lock field of witness, not WitnessArgs. Document updated:
> Please note, every element in inner_wintess, actually is a piece of data from lock field of WitnessArgs.

2023-05-15 05:57 UTC, XuJiandong commented on contracts/ckb-combine-lock-v2/src/entry.rs
> +                return Err(Error::UnlockFailed);
It's better to add `warn!` here.

2023-05-15 07:25 UTC, XuJiandong requested changes

2023-05-15 07:29 UTC, mohanson commented on contracts/ckb-combine-lock-v2/src/entry.rs
> +        return Ok(ckb_std::env::argv()[0].to_bytes().into());
Right

2023-05-16 06:05 UTC, XuJiandong requested changes

2023-05-16 06:07 UTC, XuJiandong approved these changes

2023-05-16 06:14 UTC, merged